### ISSUE TITLE
[Error]ImportError: No module named 'errors'

### ISSUE THREAD

**Issue by yangruihan** [xlzd/xart#1]
环境：Python 3.5.2
描述：
我使用`pip install xart`进行安装
`xart hello world`时报错：

`Traceback (most recent call last):
  File "/Users/yangruihan/.pyenv/versions/pyenv_3_5_2/bin/xart", line 11, in <module>
    load_entry_point('xart==0.1.8', 'console_scripts', 'xart')()
  File "/Users/yangruihan/.pyenv/versions/3.5.2/envs/pyenv_3_5_2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/yangruihan/.pyenv/versions/3.5.2/envs/pyenv_3_5_2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/Users/yangruihan/.pyenv/versions/3.5.2/envs/pyenv_3_5_2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/Users/yangruihan/.pyenv/versions/3.5.2/envs/pyenv_3_5_2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/yangruihan/.pyenv/versions/3.5.2/envs/pyenv_3_5_2/lib/python3.5/site-packages/xart/__init__.py", line 11, in <module>
    import errors
ImportError: No module named 'errors'`

**Comment by xlzd** [comment]
先暂时使用 Python2 吧，后续有空了再查查看原因~~~

**Comment by rabitdash** [comment]
我提交了一个解决了Python3运行问题的pull request，@yangruihan的问题也解决了
