### ISSUE TITLE
no module named "errors"

### ISSUE THREAD

**Issue by a7hybnj2** [xlzd/xart#8]
I can run the init.py with python but I cannot run with just 'xart' command. It seems like maybe a python python3 issue but I don't know.

```
/u/l/l/p/s/xart ▶︎︎ python __init__.py 
_________________________
                         
                         
---|/----__----)__---_/_-
   |   /   )  /   )  /   
__/|__(___(__/______(_ __
 /                       
                         
/u/l/l/p/s/xart ▶︎︎ python __init__.py -h
usage: __init__.py [-h] [-f FONT] [-c COLOR] [-i] [-s] [-l] [-v]

xart : generate art ascii texts.

optional arguments:
  -h, --help            show this help message and exit
  -f FONT, --font FONT  font to render with, default random
  -c COLOR, --color COLOR
                        font color, default WHITE, all : BLACK, RED, GREEN,
                        YELLOW, BLUE, PURPLE, CYAN, GRAY, WHITE
  -i, --info            show information of given font
  -s, --show            show random fonts
  -l, --list            list all supported fonts
  -v, --version         version
/u/l/l/p/s/xart ▶︎︎ xart -h
Traceback (most recent call last):
  File "/usr/local/bin/xart", line 5, in <module>
    from xart import main
  File "/usr/local/lib/python3.7/site-packages/xart/__init__.py", line 11, in <module>
    import errors
ModuleNotFoundError: No module named 'errors'
/u/l/l/p/s/xart ▶︎︎ 
```

**Comment by a7hybnj2** [comment]
for a temporary fix I just made and alias for "python /usr/local/lib/python3.7/site-packages/xart/__init__.py" but I am sure there is a better way.
